### ISSUE TITLE
failed to run SQL migration: failed to execute SQL query

### ISSUE THREAD

**Issue by nlypage** [eduardolat/pgbackweb#4]
![image](https://github.com/user-attachments/assets/24019b0c-1b82-4908-954b-07fd043c915d)

**Comment by eduardolat** [comment]
What version are you using? Please try to use the latest version published on Docker Hub.

Have you modified the migrations? It should actually work fine, since both columns are of UUID type.

![image](https://github.com/user-attachments/assets/e4d739ab-ef26-4a01-a29c-afd6dee19361)
![image](https://github.com/user-attachments/assets/2f2ae60a-b7f9-4b57-94b4-f30a73d17d6e)

**Comment by nlypage** [comment]
Я использую последнюю версию с dockerhub, как в вашем примере, я не менял миграции

**Comment by nlypage** [comment]
I am using the latest version from dockerhub, I have not changed the migrations

**Comment by eduardolat** [comment]
Can you please try the new release in completly new environment? it should work
